### PR TITLE
test: fix CI

### LINKED ISSUE #61: Fix failing tests on transformers coverage
Tests added through this [PR](https://github.com/BharatSahAIyak/packages/pull/43) need to be fixed to reflect new changes in transformers.

### PR DESCRIPTION
**Pull request by dhruv-1001**
fixes #61 
Modified tests & transformers to fix failing tests

### CODE REVIEW

File: packages/transformers/src/modules/generic/llm/llm.transformer.ts [hunk 1]
```diff
@@ -108,7 +108,13 @@ export class LLMTransformer implements ITransformer {
             }) || '';
         }
         let systemInstructions = xmsg.transformer?.metaData?.prompt || this.config.prompt || 'You are am assistant who helps with answering questions for users based on the search results. If question is not relevant to search reults/corpus, refuse to answer';
-        systemInstructions = systemInstructions?.replace('{{date}}', moment().format('MMM DD, YYYY (dddd)'))
+        if (typeof systemInstructions === 'object') {
```
Comment (chinmoy12c) [inline packages/transformers/src/modules/generic/llm/llm.transformer.ts:111]: `systemInstructions` would always be a `string`

File: packages/transformers/src/modules/generic/llm/stream/stringHelper.ts [hunk 2]
```diff
@@ -10,3 +10,5 @@ exports.endsWithChar = function ends_with_char(word: any, c: any) {
 exports.endsWith = function ends_with(word: any, end: any) {
     return word.slice(word.length - end.length) === end;
 };
+
+export {}
```
Comment (chinmoy12c) [inline packages/transformers/src/modules/generic/llm/stream/stringHelper.ts:14]: This will break, please do a sanity check by building packages(should not encounter warnings) and then linking in orchestrator.

**Review by chinmoy12c — CHANGES_REQUESTED** [review]

**Review by chinmoy12c — APPROVED** [review]
